#!/bin/sh

CONFIG_NAME_FS="wpmfs"
CONFIG_NAME_PROC="wpmfs_proc"

CONFIG_PATH_FS="/mnt/$CONFIG_NAME_FS"
CONFIG_PATH_PROC="/proc/$CONFIG_NAME_PROC"
CONFIG_PATH_PMEM_DEV="/dev/pmem0"

CONFIG_FS_DBGMASK=$((0x00000000))
CONFIG_FS_SIZE_JOURNAL=256M
CONFIG_FS_WL_SWITCH=2
